// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNU8t2fBn_duW3rnO2Y3JQ8ImiLab3IIo',
    appId: '1:1093679037666:web:fb172d91ffd1f6cb89b2bb',
    messagingSenderId: '1093679037666',
    projectId: 'quran-e-aziz-8ee51',
    authDomain: 'quran-e-aziz-8ee51.firebaseapp.com',
    storageBucket: 'quran-e-aziz-8ee51.appspot.com',
    measurementId: 'G-07K3K08N5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkh15gWOeUWu8wVStfq0Jm7SOxQwOs_w',
    appId: '1:1093679037666:android:5274e4ac713c997189b2bb',
    messagingSenderId: '1093679037666',
    projectId: 'quran-e-aziz-8ee51',
    storageBucket: 'quran-e-aziz-8ee51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_-XhoQ4jJb6NaX1WxKRHXCYBJ7yiq5c',
    appId: '1:1093679037666:ios:9dc58959850bf82289b2bb',
    messagingSenderId: '1093679037666',
    projectId: 'quran-e-aziz-8ee51',
    storageBucket: 'quran-e-aziz-8ee51.appspot.com',
    iosBundleId: 'com.example.quranAziz',
  );

}